
import java.util.Formatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PabloJavier
 */
public class Coloracion extends javax.swing.JFrame {

    Vertices vertices;
    public int matriz[][];
    
    /**
     * Creates new form Coloracion
     */
    public Coloracion()
    {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Coloracion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        initComponents();
    }

    private void llenarResultados(int backtraking[][], int coloresB, long tBacktraking,int greedy[][], int coloresG, long tGreedy){
        String formato = "\t\t (%-5.5s) \t (%-5.5s)\n";
        Formatter fmt = new Formatter();
        for(int i =0; i < backtraking[0].length; i++){
            String back = backtraking[0][i] + ", " + backtraking[1][i];
            String greed = greedy[0][i] + ", " + greedy[1][i];
            fmt.format(formato, back, greed);            
        }
        String titulo = "\t    Backtraking \t Greedy\n";
        formato= "\t\t %5s           %5s\n";
        fmt.format(formato, "C: "+ coloresB, "C: "+ coloresG);
        formato= "\t\t %5s   %5s\n";
        fmt.format(formato, "T: "+ tBacktraking + " ns  ", "T: "+ tGreedy + " ns  ");
        
        textResultado.setText(titulo + fmt.toString());
    }
    
    public void generarResultado(){

        //BACKTRAKING
        long tiempoB = 0;
        
        //Crear la clase
        GraphColorer colorador = new GraphColorer();
        colorador.encontrado = false;
        colorador.llenarGrafo(matriz);
        
        //Ciclo iterando desde un color
        boolean sinColorear = true;
        int num = 0;
        tiempoB = System.nanoTime();
        while(sinColorear){
            colorador.mColoring(1);
            
            if(colorador.encontrado){
                tiempoB = System.nanoTime() - tiempoB;
                sinColorear = false;
            }
            else{
                colorador.reiniciar();
            }
        }
                
        //Greedy
        long tiempoG;
        
        GreedyColorer greedy = new GreedyColorer(matriz);

        tiempoG = System.nanoTime();
        greedy.colorear();
        tiempoG = System.nanoTime() - tiempoG;
        
        llenarResultados(colorador.resultado, colorador.m, tiempoB,
                            greedy.resultado, greedy.colores, tiempoG);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        labelVertices = new javax.swing.JLabel();
        textCantidad = new javax.swing.JTextField();
        btnVertices = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelVertices.setText("Cantidad de vertices:");

        textCantidad.setText("4");
        textCantidad.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                textCantidadActionPerformed(evt);
            }
        });

        btnVertices.setText("Ingresar Vertices");
        btnVertices.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnVerticesActionPerformed(evt);
            }
        });

        textResultado.setColumns(20);
        textResultado.setRows(5);
        jScrollPane1.setViewportView(textResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVertices)
                        .addGap(18, 18, 18)
                        .addComponent(labelVertices)
                        .addGap(18, 18, 18)
                        .addComponent(textCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 91, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVertices)
                    .addComponent(textCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVertices))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textCantidadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_textCantidadActionPerformed
    {//GEN-HEADEREND:event_textCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCantidadActionPerformed

    private void btnVerticesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnVerticesActionPerformed
    {//GEN-HEADEREND:event_btnVerticesActionPerformed
        if(vertices != null){
            vertices.dispose();
        }
        int num;
        try{
            num = Integer.parseInt(textCantidad.getText());
        }catch(Exception e){
            num = 4;
        }
        vertices= new Vertices(num, this);
    }//GEN-LAST:event_btnVerticesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Coloracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Coloracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Coloracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Coloracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                new Coloracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVertices;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelVertices;
    private javax.swing.JTextField textCantidad;
    private javax.swing.JTextArea textResultado;
    // End of variables declaration//GEN-END:variables
}
